---
- hosts: web
  user: vagrant
  vars_files:
    - vars/vars.yml
  roles:
    - common/tools
    - common/selinux
    - common/net
    - nodejs
    - rails/rbenv
    - rails/ruby
    - deploy/marriage
    - deploy/rails
    - deploy/nodejs
