- name: Install ruby
  shell: >-
    source {{ home }}/.bash_profile ;
    VERSION=`rbenv versions | grep {{ item }}` ;
    if [ "${VERSION}" = "" ] ; then
      rbenv install {{ item }} &&
    fi
    executable=/bin/bash
  with_items: ruby_versions

- name: Change global ruby version
  shell: >-
    source {{ home }}/.bash_profile ;
    VERSION=`rbenv versions | grep {{ ruby_version }}` ;
    if [ "${VERSION}" = "" ] ; then
      rbenv global {{ ruby_version }} &&
      rbenv rehash ;
    fi
    executable=/bin/bash
