---
###################################################
#   host and roles info setting
###################################################
#shared_settings:
  #:ssh_options:
    #:user: vagrant
web:
  :ssh_options:
    :user: vagrant
  :hosts:
    - marriage
    #- marriage2
  :roles:
    - common
    - nodejs
    - rails
    - deploy
#
# another master role
#
#db:
  #:hosts:
    #- mariage
  #:roles:
    #- common
    #- nodejs
    #- rails
    #- deploy
