---
- name: Install rails dependency packages
  yum: name={{ item }} state=present
  with_items: rails_pkgs
  sudo: yes

- name: Install bundler
  gem: name=bundler executable={{ home }}/.rbenv/shims/gem user_install=False state=latest

- name: Install rails
  shell: >-
    source {{ home }}/.bash_profile ;
    if [ -e {{ deploy_dir }} ] ; then
      cd {{ deploy_dir }} &&
      bundle update ;
    fi
    executable=/bin/bash

- name: Start rails server
  shell: >-
    source {{ home }}/.bash_profile ;
    INSTALL=`which rails` ;
    if [ -e {{ deploy_dir }} ] && [ "${INSTALL}" != "" ] ; then
      cd {{ deploy_dir }} &&
      bundle exec rake assets:precompile &&
      export SECRET_KEY_BASE=$(bundle exec rake secret) &&
      bundle exec rails server -e production -d ;
    fi
    executable=/bin/bash

