---
- name: Yum update
  yum:
    name: "*"
    state: "latest"
  sudo: yes

- name: Check CentOS Version
  shell: cat /etc/redhat-release | awk '{print $4}' | awk -F'[.]' '{print $1}'
  register: centos_version
  changed_when: False
  ignore_errors: True

- name: Add yum repositories with CentOS 6
  yum: name={{ item }} state=present
  with_items: yum_repos6
  when: centos_version.stdout == "6"
  sudo: yes

- name: Add yum repositories with CentOS 7
  yum: name={{ item }} state=present
  with_items: yum_repos7
  when: centos_version.stdout == "7"
  sudo: yes

- name: Install python-selinux
  yum: name=libselinux-python state=latest
  sudo: yes

- name: Disable selinux
  selinux: state=disabled
  sudo: yes

- name: Install git
  yum: name=git state=installed
  sudo: yes

- name: Install basic develop tools
  yum: name={{ item }} state=installed
  sudo: yes
  with_items: dev_tools

- name: Check if exist firewalld
  shell: rpm -qa | grep firewalld
  register: firewalld_exist
  changed_when: False
  ignore_errors: True

- name: Start firewalld
  service: name=firewalld state=started enabled=yes
  when: firewalld_exist.stdout != ""
  sudo: yes
  notify: Wait for the server to come up

- name: Check if firewalld is running
  command: systemctl is-active firewalld
  #when: firewalld_exist.stdout != ""
  register: firewalld_result
  changed_when: False
  ignore_errors: True
  sudo: yes

- name: Set the port state
  firewalld: permanent=True port={{ item }} state=enabled
  with_items: open_ports
  when:
   - firewalld_exist.stdout != ""
   - firewalld_result.stdout == "active"
  sudo: yes
  notify: Reload firewalld
