---
- name: Yum update
  yum:
    name: "*"
    state: "latest"
  sudo: yes

- name: Check CentOS Version
  shell: cat /etc/redhat-release | grep -o -e ' [0-9]' | awk '{print $1}'
  register: centos_version
  changed_when: False
  ignore_errors: True

- name: Add yum repositories with CentOS 6
  yum: name={{ item }} state=present
  with_items: yum_repos6
  when: centos_version.stdout == "6"
  sudo: yes

- name: Add yum repositories with CentOS 7
  yum: name={{ item }} state=present
  with_items: yum_repos7
  when: centos_version.stdout == "7"
  sudo: yes

- name: Install git
  yum: name=git state=installed
  sudo: yes

- name: Install basic develop tools
  yum: name={{ item }} state=installed
  sudo: yes
  with_items: dev_tools

